name: lid_ds
root_dir: ${hydra:runtime.cwd}/data/LIS-DS
scenario: all
split_strategy: original_test_resplit
resplit_source_split: test
direction_filter: ">"
keep_only_successful_parsed_lines: true
transfer:
  enabled: false
  source_scenario: Bruteforce_CWE-307
  target_scenario: CVE-2014-0160
  source_strategy: resplit
  source_train_split: train
  source_val_split: validation
  source_resplit_split: test
  target_test_split: test
